// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreVueJsPOC.DAL;

namespace NetCoreVueJsPOC.DAL.Migrations
{
    [DbContext(typeof(NetCoreVueJsPOCContext))]
    partial class NetCoreVueJsPOCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("NetCoreVueJsPOC.Entities.DataModel.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("SummaryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("NetCoreVueJsPOC.Entities.DataModel.WeatherForecastSummary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecastSummary");
                });

            modelBuilder.Entity("NetCoreVueJsPOC.Entities.DataModel.WeatherForecast", b =>
                {
                    b.HasOne("NetCoreVueJsPOC.Entities.DataModel.WeatherForecastSummary", "Summary")
                        .WithMany()
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
